### ISSUE TITLE
i have set cookie but it ask need login

### ISSUE THREAD

**Issue by shirohako** [littleneko/astost_scrapy#1]
我已经设置**0cc61_winduser** 这个cookie ,但是抓取的页面还是提示我**没有登录**
在**astost.py**中: 
self.__cookies = {'0cc61_winduser': 'XXXXXX0IPV0KXAcGUABdUlsIDFQDVgsJAwBSXVJdAQELBl8MBQJRag%3D%3D'}

**Comment by littleneko** [comment]
1. User-Agent 可能也需要修改一下，最好把那些heder全改成你浏览器上抓的
2. 另外，因为我当时是挂代理抓的，不用代理的话需要把`settings.py`里面的
```
DOWNLOADER_MIDDLEWARES = {
    'astost_scrapy.middlewares.ProxyMiddleware': 543,
}
```
注释掉
3. 数据库有需要就自建吧，代码里面应该没有建数据库的功能
